import streamlit as st
import uuid

from src.graph import run_turn
from src.llm.memory import clear_memory


# ============================================================
# PAGE CONFIG
# ============================================================

st.set_page_config(
    page_title="NMAMIT Academic Assistant",
    page_icon="🎓",
    layout="wide",
    initial_sidebar_state="collapsed"
)


# ============================================================
# SESSION STATE
# ============================================================

if "session_id" not in st.session_state:
    st.session_state.session_id = str(uuid.uuid4())

if "messages" not in st.session_state:
    st.session_state.messages = []

# Stores the current study plan generated by LangGraph
if "plan_spec" not in st.session_state:
    st.session_state.plan_spec = None


# ============================================================
# CUSTOM CSS
# ============================================================

st.markdown("""
<style>

@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&display=swap');


/* ---------- GLOBAL ---------- */

html, body, [class*="css"] {
    font-family: 'Poppins', sans-serif;
}

.stApp {
    background:
        linear-gradient(
            135deg,
            #071d49 0%,
            #0B2A6B 38%,
            #1c5ca8 72%,
            #2F6FC4 100%
        );
    color: #FFFFFF;
}


/* ---------- REMOVE STREAMLIT DEFAULTS ---------- */

#MainMenu {
    visibility: hidden;
}

footer {
    visibility: hidden;
}

header {
    background: transparent !important;
}


/* ---------- MAIN CONTAINER ---------- */

.block-container {
    max-width: 1250px;
    padding-top: 2rem;
    padding-bottom: 5rem;
}


/* ---------- TOP BAR ---------- */

.topbar {
    display: flex;
    justify-content: flex-end;
    align-items: center;
    margin-bottom: 4rem;
}


/* ---------- TOP RIGHT ---------- */

.assistant-pill {
    background: #2E2A8F;
    padding: 12px 24px;
    border-radius: 30px;
    font-size: 13px;
    font-weight: 600;
    letter-spacing: 0.5px;
}


/* ---------- HERO ---------- */

.hero {
    max-width: 900px;
}

.hero-small {
    font-size: 20px;
    font-weight: 300;
    letter-spacing: 0.5px;
    margin-bottom: 10px;
}

.hero-title {
    font-size: clamp(42px, 6vw, 78px);
    line-height: 0.98;
    font-weight: 800;
    letter-spacing: -2px;
    margin: 0 0 25px 0;
}

.hero-title span {
    color: #FDB913;
}

.hero-description {
    max-width: 760px;
    font-size: 18px;
    line-height: 1.7;
    font-weight: 300;
    color: rgba(255,255,255,0.88);
}

.hero-description strong {
    font-weight: 700;
    color: white;
}


/* ---------- CHAT AREA ---------- */

.chat-section {
    margin-top: 70px;
    padding-top: 35px;
    border-top: 1px solid rgba(255,255,255,0.18);
}

.section-label {
    font-size: 12px;
    font-weight: 600;
    letter-spacing: 2px;
    text-transform: uppercase;
    color: rgba(255,255,255,0.65);
    margin-bottom: 20px;
}


/* ---------- CHAT MESSAGES ---------- */

[data-testid="stChatMessage"] {
    background: rgba(255,255,255,0.07);
    border: 1px solid rgba(255,255,255,0.08);
    border-radius: 14px;
    padding: 10px;
    margin-bottom: 12px;
}


/* ---------- CHAT INPUT ---------- */

[data-testid="stChatInput"] {
    background: transparent;
}

[data-testid="stChatInput"] textarea {
    background: rgba(255,255,255,0.96) !important;
    color: #111111 !important;
    border: none !important;
    border-radius: 4px !important;
    font-family: 'Poppins', sans-serif !important;
    padding: 16px !important;
}

[data-testid="stChatInput"] textarea::placeholder {
    color: #666666 !important;
}


/* ---------- SOURCES ---------- */

.source-card {
    background: rgba(255,255,255,0.08);
    border-left: 4px solid #FDB913;
    padding: 12px 15px;
    margin: 8px 0;
    border-radius: 2px;
    font-size: 13px;
}

.source-title {
    font-weight: 600;
    color: white;
}

.source-meta {
    color: rgba(255,255,255,0.65);
    font-size: 11px;
    margin-top: 3px;
}


/* ---------- CLEAR BUTTON ---------- */

div.stButton > button {
    border-radius: 30px;
    border: 1px solid rgba(255,255,255,0.3);
    background: transparent;
    color: white;
    font-family: 'Poppins', sans-serif;
    font-weight: 500;
}

div.stButton > button:hover {
    border-color: #FDB913;
    color: #FDB913;
}


/* ---------- MOBILE ---------- */

@media (max-width: 768px) {

    .block-container {
        padding-left: 1.2rem;
        padding-right: 1.2rem;
    }

    .topbar {
        margin-bottom: 2.5rem;
    }

    .hero-title {
        font-size: 46px;
    }

    .hero-description {
        font-size: 15px;
    }
}

</style>
""", unsafe_allow_html=True)


# ============================================================
# TOP BAR
# ============================================================

st.html("""
<div class="topbar">

    <div class="assistant-pill">
        ACADEMIC ASSISTANT
    </div>

</div>
""")


# ============================================================
# HERO
# ============================================================

st.html("""
<div class="hero">

    <div class="hero-small">
        Your academic companion at NMAMIT
    </div>

    <div class="hero-title">
        ASK. <span>LEARN.</span><br>
        PLAN.
    </div>

    <div class="hero-description">
        Get reliable answers about your
        <strong>curriculum, regulations, examinations and academics</strong>
        using information from official NMAMIT resources.
    </div>

</div>
""")


# ============================================================
# CHAT SECTION
# ============================================================

st.html("""
<div class="chat-section">
    <div class="section-label">
        Academic Assistant
    </div>
</div>
""")


# ============================================================
# DISPLAY PREVIOUS MESSAGES
# ============================================================

for message in st.session_state.messages:

    with st.chat_message(message["role"]):

        st.markdown(message["content"])

        if message.get("sources"):

            with st.expander("View sources"):

                for source in message["sources"]:

                    title = source.get(
                        "title",
                        source.get("source", "NMAMIT Document")
                    )

                    page = source.get("page", "")

                    st.html(
                        f"""
                        <div class="source-card">
                            <div class="source-title">
                                {title}
                            </div>
                            <div class="source-meta">
                                {f"Page {page}" if page else ""}
                            </div>
                        </div>
                        """
                    )


# ============================================================
# CHAT INPUT
# ============================================================

question = st.chat_input(
    "Ask your academic question..."
)


# ============================================================
# PROCESS QUESTION
# ============================================================

if question:

    # Display user message
    st.session_state.messages.append({
        "role": "user",
        "content": question
    })

    with st.chat_message("user"):
        st.markdown(question)


    # --------------------------------------------------------
    # Generate response through LangGraph
    # --------------------------------------------------------

    with st.chat_message("assistant"):

        with st.spinner("Thinking..."):

            result = run_turn(
                message=question,
                session_id=st.session_state.session_id,
                plan_spec=st.session_state.plan_spec
            )

        answer = result.get("answer", "")
        sources = result.get("sources", [])
        intent = result.get("intent")
        warnings = result.get("warnings", [])

        # Save updated study plan if one was created/modified
        if result.get("plan_spec") is not None:
            st.session_state.plan_spec = result["plan_spec"]

        st.markdown(answer)


        # ----------------------------------------------------
        # Sources
        # ----------------------------------------------------

        if sources:

            with st.expander("View sources"):

                for source in sources:

                    title = source.get(
                        "title",
                        source.get("source", "NMAMIT Document")
                    )

                    page = source.get("page", "")

                    st.html(
                        f"""
                        <div class="source-card">
                            <div class="source-title">
                                {title}
                            </div>

                            <div class="source-meta">
                                {f"Page {page}" if page else ""}
                            </div>
                        </div>
                        """
                    )


        # ----------------------------------------------------
        # Warnings
        # ----------------------------------------------------

        if warnings:

            for warning in warnings:
                st.warning(warning)


    # --------------------------------------------------------
    # Save assistant message
    # --------------------------------------------------------

    st.session_state.messages.append({
        "role": "assistant",
        "content": answer,
        "sources": sources
    })


# ============================================================
# CLEAR CHAT
# ============================================================

st.markdown("<br>", unsafe_allow_html=True)

if st.button("🗑 Clear conversation"):

    clear_memory(st.session_state.session_id)

    st.session_state.messages = []

    # Clear active study plan as well
    st.session_state.plan_spec = None

    st.rerun()